

<div class="container my-5">
    <div class="row" style="margin-top: 200px;">
        <div class="col align-self-center text-center">
            <img src="Images/105157484_padded_logo.png" class="img-fluid" style="max-width: 500px;">

            <div style="margin-top: 50px;">
                <p class="lead mt-3"style="font-size: 1.2em; color: #333300;">"Join our community of electric car users and share your driveway charger for a fee.
                    Find available chargers in your area by postcode and never worry about running low on battery again.
                    Sign up now and start charging!"</p>
            </div>

        </div>
    </div>
</div>