<!-- Bootstrap Modal / pop up logging box. This is set to aria-hidden="true", so it would show
only if the login button in the navbar is clicked-->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Login</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <form method="post" action="" class="form text-primary">

                    <label for="username">Username (email)</label>
                    <input class="row" type="text" name="username">
                    <label for="password">Password</label>
                    <input class="row" type="text" name="password">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <input type="submit" class="btn btn-primary" name="loginButton" value="Login">
            </div>

            </form>
        </div>
    </div>
</div>