
<section class="vh-100" style="background-color: #2779e2;">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-xl-9">
                <h1 class="text-white mb-4">Register</h1>
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body">

                        <form method="post" action="registrationController.php" enctype="multipart/form-data">
                        <div class="row align-items-center pt-4 pb-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">Full name</h6>
                                <h6 class="mb-0">(required)</h6>
                            </div>
                            <div class="col-md-9 pe-5">
                                <input type="text" class="form-control form-control-lg" name="name" id="name" required/>
                            </div>
                        </div>


                        <hr class="mx-n3">
                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">Email address</h6>
                                <h6 class="mb-0">(required)</h6>
                            </div>
                            <div class="col-md-9 pe-5">
                                <input type="email" class="form-control form-control-lg" name="email" id="email"
                                       placeholder="example@example.com" required>
                            </div>
                        </div>

                            <hr class="mx-n3">
                            <div class="row align-items-center py-3">
                                <div class="col-md-3 ps-5">
                                    <h6 class="mb-0">Password</h6>
                                    <h6 class="mb-0">(required)</h6>
                                </div>
                                <div class="col-md-9 pe-5">
                                    <input type="password" class="form-control form-control-lg" name="password"
                                           id="password" placeholder="password" aria-describedby="pas" required/>
                                    <div class="small text-muted mt-2"
                                         id="pas">*Between 8 and 60 characters. Minimum one upper case,
                                        one lower case and one digit.</div>

                                </div>
                            </div>


                            <hr class="mx-n3">
                            <div class="row align-items-center py-3">
                                <div class="col-md-3 ps-5">
                                    <h6 class="mb-0">Phone Number</h6>
                                </div>
                                <div class="col-md-9 pe-5">
                                    <input type="tel" class="form-control form-control-lg"
                                           name="phone" id="phone" placeholder="Enter Phone number"/>
                                </div>
                            </div>


                        <hr class="mx-n3">
                        <div class="row align-items-center py-3">
                            <div class="col-md-3 ps-5">
                                <h6 class="mb-0">Upload Profile Picture</h6>
                            </div>
                            <div class="col-md-9 pe-5">
                                <input type="file" class="form-control form-control-lg" name="image" id="formFileLg" />
                                <div class="small text-muted mt-2">Upload your profile image</div>
                            </div>

                        </div>

                            <hr class="mx-n3">
                        <div class="px-5 py-4">


                            <button class="btn btn-primary btn-lg"><a
                                        href="index.php" class="text-decoration-none text-white">Close</a></button>
                            <button type="submit" class="btn btn-primary btn-lg" name="register"
                                    value="register">Submit</button>



                        </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

